# 'fullnameOverride' is deprecated. Use 'deployment.instance_name' instead.
# This is only supported for backward compatibility and will be removed in a future version.
# If 'fullnameOverride' is not "kiali" and 'deployment.instance_name' is "kiali",
# then 'deployment.instance_name' will take the value of 'fullnameOverride' value.
# Otherwise, 'fullnameOverride' is ignored and 'deployment.instance_name' is used.
fullnameOverride: "kiali"

# This is required for "openshift" auth strategy.
# You have to know ahead of time what your Route URL will be because
# right now the helm chart can't figure this out at runtime (it would
# need to wait for the Kiali Route to be deployed and for OpenShift
# to start it up). If someone knows how to update this helm chart to
# do this, a PR would be welcome.
kiali_route_url: ""

#
# Settings that mimic the Kiali CR which are placed in the ConfigMap.
# Note that only those values used by the Helm Chart will be here.
#

istio_namespace: ns-observability # default is where Kiali is installed

auth:
  openid: {}
  openshift: {}
  strategy: ""

deployment:
  # This only limits what Kiali will attempt to see, but Kiali Service Account has permissions to see everything.
  # For more control over what the Kial Service Account can see, use the Kiali Operator
  accessible_namespaces:
    - "**"
  additional_service_yaml: {}
  affinity:
    node: {}
    pod: {}
    pod_anti: {}
  configmap_annotations: {}
  custom_secrets: []
  host_aliases: []
  hpa:
    api_version: "autoscaling/v2"
    spec: {}
  image_digest: "" # use "sha256" if image_version is a sha256 hash (do NOT prefix this value with a "@")
  image_name: quay.io/kiali/kiali
  image_pull_policy: "Always"
  image_pull_secrets: []
  image_version: v1.72.0 # version like "v1.39" (see: https://quay.io/repository/kiali/kiali?tab=tags) or a digest hash
  ingress:
    additional_labels: {}
    class_name: "alb" # TCN modified. Default: "nginx"
    #enabled:
    override_yaml:
      metadata:
        annotations: # TCN modified. Default: None
          kubernetes.io/ingress.class: alb
          alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:567925872059:certificate/b7a479b7-8e63-4e40-927b-fe918692a4a4
          alb.ingress.kubernetes.io/security-groups: sg-01cd8d738b8b2f506
          alb.ingress.kubernetes.io/subnets: subnet-123d1c7a,subnet-61fb6f2d
          alb.ingress.kubernetes.io/group.name: ingress-common-ialb
          alb.ingress.kubernetes.io/healthcheck-path: /health
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
          alb.ingress.kubernetes.io/scheme: internal
          alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
          alb.ingress.kubernetes.io/ssl-redirect: "443"
          alb.ingress.kubernetes.io/success-codes: "200"
          alb.ingress.kubernetes.io/target-type: instance
  instance_name: "kiali"
  logger:
    log_format: "text"
    log_level: "info"
    time_field_format: "2006-01-02T15:04:05Z07:00"
    sampler_rate: "1"

  nodeSelector: # TCN Modified. Default: {}
    nodegroup: ng-cluster

  pod_annotations: {}
  pod_labels: {}
  priority_class_name: ""
  replicas: 1
  resources:
    requests:
      cpu: "10m"
      memory: "64Mi"
    limits:
      memory: "1Gi"
  secret_name: "kiali"
  security_context: {}
  service_annotations: {}
  service_type: "NodePort" # TCN modified. Default: "ClusterIP"
  tolerations: []
  version_label: v1.72.0 # v1.39 # v1.39.0 # see: https://quay.io/repository/kiali/kiali?tab=tags
  view_only_mode: false

external_services:
  custom_dashboards:
    enabled: true
  istio:
    root_namespace: ""

identity:
  {}
  #cert_file:
  #private_key_file:

kiali_feature_flags:
  certificates_information_indicators:
    enabled: true
    secrets:
      - cacerts
      - istio-ca-secret
  clustering:
    autodetect_secrets:
      enabled: true
      label: "kiali.io/multiCluster=true"
    clusters: []
  disabled_features: []
  validations:
    ignore: ["KIA1301"]

login_token:
  signing_key: ""

server:
  port: 20001
  metrics_enabled: false
  metrics_port: 9090
  web_root: ""
  web_fqdn: "kic-st-kiali.lgthinq.com" # TCN modified. Default: ""
